version: '3.7'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: typeg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
